x-common-config: &common-config
  image: ghcr.io/${REPO}/${NAME}:${GIT_COMMIT}
  working_dir: /home/jovyan/workspace
  environment: &common-env
    RENV_PATHS_CACHE: /home/jovyan/workspace/renv/library/
    # set defaults for REPO, NAME, and GIT_COMMIT
    REPO: ${REPO-graticule}
    NAME: ${NAME-pharmasug-demo}
    GIT_COMMIT: ${GIT_COMMIT-latest}

x-base-image-build: &base-image-build
  context: .
  platforms:
    - linux/amd64
  args:
    GIT_COMMIT: ${GIT_COMMIT}
  tags:
    - "ghcr.io/${REPO}/${NAME}:${GIT_COMMIT}"

x-notebook-cmd: &notebook-cmd |
  /bin/bash -c "set -e && \
  make setup && \
  papermill source/papermill.ipynb output/notebooks/papermill.ipynb --kernel python3"

services:
  base-image:
    build: *base-image-build
  
  run-notebook:
    <<: *common-config
    build: *base-image-build
    environment:
      <<: *common-env
    command: *notebook-cmd
    volumes:
      - .:/home/jovyan/workspace
      - /home/runner/work/_temp/renv/library:/home/jovyan/workspace/renv/library:rw

  ### Local commands ###
  local-interactive:
    <<: *common-config
    build: *base-image-build
    environment:
      <<: *common-env
    command: /bin/bash
    volumes:
      - .:/home/jovyan/workspace
    tty: true
    stdin_open: true
  
  local-notebook:
    <<: *common-config
    build: *base-image-build
    environment:
      <<: *common-env
    command: *notebook-cmd
    volumes:
      - .:/home/jovyan/workspace
