x-common-config: &common-config
  image: ghcr.io/${REPO}/${NAME}:${GCR_TAG}
  working_dir: /home/jovyan/workspace
  environment: &common-env
    NB_PATH: /home/jovyan/workspace/source
    RENV_PATHS_CACHE: /home/jovyan/workspace/renv/library/

x-base-image-build: &base-image-build
  context: .
  platforms:
    - linux/amd64
  args:
    GIT_COMMIT: ${GCR_TAG}
  tags:
    - "ghcr.io/${REPO}/${NAME}:latest"
    - "ghcr.io/${REPO}/${NAME}:${GCR_TAG}"

x-notebook-cmd: &notebook-cmd |
  /bin/bash -c "set -e && \
  make setup && \
  papermill ${NB_PATH}/papermill.ipynb output/notebooks/papermill.ipynb --kernel python3"

services:
  base-image:
    build: *base-image-build
  
  run-notebook:
    <<: *common-config
    build: *base-image-build
    environment:
      <<: *common-env
    command: *notebook-cmd
    volumes:
      - .:/home/jovyan/workspace
      - /home/runner/work/_temp/renv/library:/home/jovyan/workspace/renv/library:rw

  ### Local commands ###
  local-interactive:
    <<: *common-config
    env_file: .env
    command: /bin/bash
    volumes:
      - .:/home/jovyan/workspace
    tty: true
    stdin_open: true
  
  local-notebook:
    <<: *common-config
    build: *base-image-build
    env_file: .env
    command: *notebook-cmd
    volumes:
      - .:/home/jovyan/workspace
